// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.appscpj.domain;

import br.com.appscpj.domain.AdvogadoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AdvogadoIntegrationTest_Roo_Configurable {
    
    declare @type: AdvogadoIntegrationTest: @Configurable;
    
}
