// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.appscpj.domain;

import br.com.appscpj.dao.ParteDao;
import br.com.appscpj.domain.ParteDataOnDemand;
import br.com.appscpj.domain.ParteIntegrationTest;
import br.com.appscpj.service.ParteService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParteIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParteIntegrationTest: @Transactional;
    
    @Autowired
    ParteDataOnDemand ParteIntegrationTest.dod;
    
    @Autowired
    ParteService ParteIntegrationTest.parteService;
    
    @Autowired
    ParteDao ParteIntegrationTest.parteDao;
    
    @Test
    public void ParteIntegrationTest.testCountAllPartes() {
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", dod.getRandomParte());
        long count = parteService.countAllPartes();
        Assert.assertTrue("Counter for 'Parte' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParteIntegrationTest.testFindParte() {
        Parte obj = dod.getRandomParte();
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parte' failed to provide an identifier", id);
        obj = parteService.findParte(id);
        Assert.assertNotNull("Find method for 'Parte' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Parte' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParteIntegrationTest.testFindAllPartes() {
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", dod.getRandomParte());
        long count = parteService.countAllPartes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Parte', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Parte> result = parteService.findAllPartes();
        Assert.assertNotNull("Find all method for 'Parte' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Parte' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParteIntegrationTest.testFindParteEntries() {
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", dod.getRandomParte());
        long count = parteService.countAllPartes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Parte> result = parteService.findParteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Parte' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Parte' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParteIntegrationTest.testFlush() {
        Parte obj = dod.getRandomParte();
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parte' failed to provide an identifier", id);
        obj = parteService.findParte(id);
        Assert.assertNotNull("Find method for 'Parte' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParte(obj);
        Integer currentVersion = obj.getVersion();
        parteDao.flush();
        Assert.assertTrue("Version for 'Parte' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParteIntegrationTest.testUpdateParteUpdate() {
        Parte obj = dod.getRandomParte();
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parte' failed to provide an identifier", id);
        obj = parteService.findParte(id);
        boolean modified =  dod.modifyParte(obj);
        Integer currentVersion = obj.getVersion();
        Parte merged = parteService.updateParte(obj);
        parteDao.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Parte' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParteIntegrationTest.testSaveParte() {
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", dod.getRandomParte());
        Parte obj = dod.getNewTransientParte(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Parte' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Parte' identifier to be null", obj.getId());
        parteService.saveParte(obj);
        parteDao.flush();
        Assert.assertNotNull("Expected 'Parte' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParteIntegrationTest.testDeleteParte() {
        Parte obj = dod.getRandomParte();
        Assert.assertNotNull("Data on demand for 'Parte' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parte' failed to provide an identifier", id);
        obj = parteService.findParte(id);
        parteService.deleteParte(obj);
        parteDao.flush();
        Assert.assertNull("Failed to remove 'Parte' with identifier '" + id + "'", parteService.findParte(id));
    }
    
}
