// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.appscpj.domain;

import br.com.appscpj.domain.ParteDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParteDataOnDemand_Roo_Configurable {
    
    declare @type: ParteDataOnDemand: @Configurable;
    
}
